name: Izem Runtime CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Nim
      uses: iffy/install-nim@v5
      with:
        version: '2.0.0'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.0-dev

    - name: Install nim dependencies
      run: make deps
    
    - name: Build project
      run: make
    
    - name: Run basic test
      run: |
        echo 'console.log("Hello, World!");' > test.js
        ./izem test.js | grep "Hello, World!"